### ISSUE TITLE
Cannot find version 0.0.10

### ISSUE THREAD

**Issue by bnadlerjr** [marksteve/flask-oauth2-login#4]
I was previously using version 0.0.10 until this morning when I started getting errors in my CI build that version 0.0.10 could not be found. I've downgraded to 0.0.9, but was 0.0.10 pulled from PyPI for some reason?

**Comment by marksteve** [comment]
Hi bnadlerjr! Version 0.0.10 doesn't exist. This project is also currently unmaintained :)
